tickers:
- ticker: SOFI
  source: screener
  discovery_date: '2026-04-18'
- ticker: RKLB
  source: screener
  discovery_date: '2026-04-18'
- ticker: RDDT
  source: screener
  discovery_date: '2026-04-18'
- ticker: ASTS
  source: screener
  discovery_date: '2026-04-19'
- ticker: HIMS
  source: screener
  discovery_date: '2026-04-19'
